remove non-working Jupyter magic.py
This file has not been touched substantively in a few years, is not
documented, and no longer works.

If these missing dependencies are added to pyproject.toml:

 * ipython-sql
 * sql

Then the user can do the following in a notebook/console started from
the mycli repo root:

    In [1]: %load_ext sql
    In [2]: %load_ext mycli.magic
    In [3]: %sql mysql+pymysql://mycli:password@localhost:3306/mysql

However, upon executing a query with the magic

    In [4]: %mycli show tables

we find that magic.py has

    mycli: MyCli = conn._mycli

but mycli has long since been refactored, such that

    AttributeError: 'Connection' object has no attribute '_mycli'

and it throws similarly for

     u = conn.session.engine.url

Given that this is not working, not maintained, and not documented, we
should be comfortable deleting it without a deprecation cycle.

In the future, if this functionality is desired, it should probably be
implemented in a separate library which takes mycli as a dependency.
That way it could be more discoverable on PyPi, and could declare
additional dependencies needed only in the notebook context.